### PR TITLE
Stock YFC500 (STM Variant)

### PR DESCRIPTION
**Pull request by Apehaenger**
Hi Clemens.

Not finally ready, but done so far!

~The LED and Button order is still cowlicked :-/
Checked KiCad schematics, PCB and sources, but in my understanding they don't fit together. Also CoverUITest's setBars4() and setBars7() don't harmonize in my view with KiCad stuff.
However, I build the STM stuff flexible, and once I know the real LED & Button IDs, it will be quite easy to change.~

ST-Link Debugger is also in PlatformIO.ini now (got problems with picoprobe's uart when not in debug mode).

Till now I tested only with UART & CoverTestUI, ~but as soon as we/I identified the real LED & Button IDs,~ I would connect to mainboard, and if you're interested, I can offer to write afterwards a detailed Readme with instructions and pictures.

BTW: To get Home and Play button, I moved R33 (0 Ohm bridge) to R34, as well as R37 to R42.
Bridging R34 and R42 might also be enough, but by moving, you also remove the lane to J6 which looked more save to me.

Cabling Stock Cover UI (mine is a RM-ECOW-V1.3.0, 2020.05.08, STM32F030R8):
J6 Pin 1 = TX
J6 Pin 3 = RX
J6 Pin 7 = GND
J6 Pin 9 = 5V

And not to forget: Could compile your Pico-SDK code, but due to lack of an OM-CoverUI I couldn't test :-;

### CODE REVIEW

**Comment by Apehaenger** [comment]
Found promising LED definition within LowLevel code, and yeah, now it look like expected.
Also made a separate commit for CoverUITest which reflects the LED order within LowLevel

**Comment by Apehaenger** [comment]
Hi Clemens!

Short update: "Don't pull for now"... looks like I fully switch from HAL to arduino framework to get STM and GD handled together ;-)

**Comment by Apehaenger** [comment]
As informed.
Will do a new one once I get framework-arduino and framwork-arduinogd32 handled together (some how ;-))

**Comment by rfvermut** [comment]
Ok, looking forward to it

**Pull request closed without merging**
